// fig-assembled: DO NOT hand-edit — generated by the website skill's
// assemble_site.py. Source of truth: src/data/manifest.json + the content
// module. Edit those and re-run the assembler; it refuses to overwrite a
// file missing this header unless --force is passed.

import { Toaster } from '@/components/ui/sonner'

import { StoreApp } from '@/components/site/StoreApp'

export default function App() {
  return (
    <>
      <main>
        <StoreApp />
      </main>
      <Toaster />
    </>
  )
}
